webtalk_init -webtalk_dir C:\\Xilinx\\Projects\\pat_testharness-testsocket\\pat_testharness-testsocket.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Feb 18 13:40:54 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210869449_175113628_0_436" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "oliqujo6g6upqt3h0004sdhhh6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770S CPU @ 3.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3093 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1424200734115" -context "sdk\\\\hardware/1424200734115"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1424200734115"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1424200734115"
webtalk_add_data -client sdk -key VivadoVersion -value "2014.4" -context "sdk\\\\hardware/1424200734115"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1424200734115"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1424200734115"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1424200734115"
webtalk_add_data -client sdk -key uid -value "1424200740786" -context "sdk\\\\bsp/1424200740786"
webtalk_add_data -client sdk -key hwid -value "1424200734115" -context "sdk\\\\bsp/1424200740786"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1424200740786"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1424200740786"
webtalk_transmit -clientid 3696229209 -regid "210869449_175113628_0_436" -xml C:\\Xilinx\\Projects\\pat_testharness-testsocket\\pat_testharness-testsocket.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Xilinx\\Projects\\pat_testharness-testsocket\\pat_testharness-testsocket.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Xilinx\\Projects\\pat_testharness-testsocket\\pat_testharness-testsocket.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
