# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {Labtools 27-2149}  -string {{ERROR: [Labtools 27-2149] File C:/Users/cssjh/LocalDocuments/Xilinx/Projects/pat_testharness/pat_testharness.runs/impl_1/design_1_wrapper.bit not found. Check file name and file permissions.}}  -suppress 
set_msg_config  -id {filemgmt 20-1741}  -string {{CRITICAL WARNING: [filemgmt 20-1741] File 'slave_attachment.vhd' is used by one or more modules, but with different contents, and may lead to unpredictable results:
* design_1_axi_gpio_0_0 (c:/Xilinx/Projects/git-pat_testharness/src/design_1/ip/design_1_axi_gpio_0_0/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd)
* design_1_axi_gpio_1_0 (c:/Xilinx/Projects/git-pat_testharness/src/design_1/ip/design_1_axi_gpio_1_0/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd)
* design_1_axi_gpio_1_1 (c:/Xilinx/Projects/git-pat_testharness/src/design_1/ip/design_1_axi_gpio_1_1/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd)
* design_1_axi_gpio_1_2 (c:/Xilinx/Projects/git-pat_testharness/src/design_1/ip/design_1_axi_gpio_1_2/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd)
* design_1_axi_gpio_1_3 (c:/Xilinx/Projects/git-pat_testharness/src/design_1/ip/design_1_axi_gpio_1_3/axi_lite_ipif_v3_0/hdl/src/vhdl/slave_attachment.vhd)
Please reset and regenerate these modules to resolve the differences, or synthesize them independently.}}  -suppress 
set_msg_config  -id {Synth 8-2537}  -string {{ERROR: [Synth 8-2537] port pwm_gpio_1 is not defined [C:/Xilinx/Projects/pat_testharness-pwm/pat_testharness-pwm.srcs/sources_1/imports/hdl/design_1_wrapper.v:92]}}  -suppress 
set_msg_config  -id {Synth 8-2537}  -string {{ERROR: [Synth 8-2537] port pwm_gpio_2 is not defined [C:/Xilinx/Projects/pat_testharness-pwm/pat_testharness-pwm.srcs/sources_1/imports/hdl/design_1_wrapper.v:93]}}  -suppress 
set_msg_config  -id {Synth 8-2537}  -string {{ERROR: [Synth 8-2537] port pwm_high is not defined [C:/Xilinx/Projects/pat_testharness-pwm/pat_testharness-pwm.srcs/sources_1/imports/hdl/design_1_wrapper.v:94]}}  -suppress 
set_msg_config  -id {Synth 8-2537}  -string {{ERROR: [Synth 8-2537] port pwm_low is not defined [C:/Xilinx/Projects/pat_testharness-pwm/pat_testharness-pwm.srcs/sources_1/imports/hdl/design_1_wrapper.v:97]}}  -suppress 
set_msg_config  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: Synthesis failed - please see the console or run log file for details}}  -suppress 
set_msg_config  -id {Coretcl 2-1279}  -string {{CRITICAL WARNING: [Coretcl 2-1279] The upgrade of IP instance 'design_1_util_ds_buf_0_3' has identified issues that may require user intervention. Please review the upgrade log 'c:/Xilinx/Projects/git-pat_testharness/src/design_1/ip/design_1_util_ds_buf_0_3/design_1_util_ds_buf_0_3.upgrade_log', and verify that the upgraded IP is correctly configured.}}  -suppress 
set_msg_config  -id {IP_Flow 19-3298}  -string {{CRITICAL WARNING: [IP_Flow 19-3298] Detected external port differences while upgrading IP 'design_1_util_ds_buf_0_0'. These changes may impact your design.}}  -suppress 
set_msg_config  -id {IP_Flow 19-3298}  -string {{CRITICAL WARNING: [IP_Flow 19-3298] Detected external port differences while upgrading IP 'design_1_util_ds_buf_0_3'. These changes may impact your design.}}  -suppress 
set_msg_config  -id {Coretcl 2-1279}  -string {{CRITICAL WARNING: [Coretcl 2-1279] The upgrade of IP instance 'design_1_util_ds_buf_0_0' has identified issues that may require user intervention. Please review the upgrade log 'c:/Xilinx/Projects/git-pat_testharness/src/design_1/ip/design_1_util_ds_buf_0_0/design_1_util_ds_buf_0_0.upgrade_log', and verify that the upgraded IP is correctly configured.}}  -suppress 

create_project -in_memory -part xc7z020clg484-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.cache/wt [current_project]
set_property parent.project_path C:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.2 [current_project]
set_property ip_repo_paths {
  C:/Xilinx/Projects/pat_testharness-testsocket.xpr/pat_testharness-testsocket/pat_testharness-testsocket.ipdefs/ip_clock_selector
  C:/Xilinx/Projects/pat_testharness-testsocket.xpr/pat_testharness-testsocket/pat_testharness-testsocket.ipdefs/ip_clock_measure
} [current_project]
add_files C:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_modes_0_1/design_1_axi_gpio_modes_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_modes_0_1/design_1_axi_gpio_modes_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_modes_0_1/design_1_axi_gpio_modes_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_dac_0_1/design_1_axi_gpio_dac_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_dac_0_1/design_1_axi_gpio_dac_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_dac_0_1/design_1_axi_gpio_dac_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_abpins_0_1/design_1_axi_gpio_abpins_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_abpins_0_1/design_1_axi_gpio_abpins_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_abpins_0_1/design_1_axi_gpio_abpins_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_pwm_0_1/design_1_axi_gpio_pwm_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_pwm_0_1/design_1_axi_gpio_pwm_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_pwm_0_1/design_1_axi_gpio_pwm_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_clock_0_1/design_1_axi_gpio_clock_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_clock_0_1/design_1_axi_gpio_clock_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_clock_0_1/design_1_axi_gpio_clock_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0_late.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files C:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib {
  C:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/imports/Projects/git-pat_testharness/src/design_1/hdl/pwm_generator.v
  C:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/imports/hdl/design_1_wrapper.v
}
read_xdc C:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/constrs_1/imports/constraints/pat_testharness-constraints-fmc.xdc
set_property used_in_implementation false [get_files C:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/constrs_1/imports/constraints/pat_testharness-constraints-fmc.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file design_1_wrapper.hwdef }
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
