# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/pat_testharness-constraints-fmc.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}]

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0}]

# IP: bd/design_1/ip/design_1_processing_system7_0_axi_periph_0/design_1_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==design_1_processing_system7_0_axi_periph_0}]

# IP: bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_100M_0}]

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0}]

# IP: bd/design_1/ip/design_1_clock_select_0_0/design_1_clock_select_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clock_select_0_0 || ORIG_REF_NAME==design_1_clock_select_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_2_1/design_1_xlslice_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_2_1 || ORIG_REF_NAME==design_1_xlslice_2_1}]

# IP: bd/design_1/ip/design_1_clock_measure_0_0/design_1_clock_measure_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clock_measure_0_0 || ORIG_REF_NAME==design_1_clock_measure_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_4_0/design_1_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_4_0 || ORIG_REF_NAME==design_1_xlslice_4_0}]

# IP: bd/design_1/ip/design_1_xlslice_5_0/design_1_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_5_0 || ORIG_REF_NAME==design_1_xlslice_5_0}]

# IP: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0}]

# IP: bd/design_1/ip/design_1_axi_gpio_modes_0_1/design_1_axi_gpio_modes_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_modes_0 || ORIG_REF_NAME==design_1_axi_gpio_modes_0}]

# IP: bd/design_1/ip/design_1_axi_gpio_dac_0_1/design_1_axi_gpio_dac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_dac_0 || ORIG_REF_NAME==design_1_axi_gpio_dac_0}]

# IP: bd/design_1/ip/design_1_xlslice_0_0_2/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_1_0_2/design_1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0}]

# IP: bd/design_1/ip/design_1_axi_gpio_abpins_0_1/design_1_axi_gpio_abpins_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_abpins_0 || ORIG_REF_NAME==design_1_axi_gpio_abpins_0}]

# IP: bd/design_1/ip/design_1_axi_gpio_pwm_0_1/design_1_axi_gpio_pwm_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_pwm_0 || ORIG_REF_NAME==design_1_axi_gpio_pwm_0}]

# IP: bd/design_1/ip/design_1_axi_gpio_clock_0_1/design_1_axi_gpio_clock_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_clock_0 || ORIG_REF_NAME==design_1_axi_gpio_clock_0}]

# IP: bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_pat_0 || ORIG_REF_NAME==design_1_clk_pat_0}]

# IP: bd/design_1/ip/design_1_util_ds_buf_bin_0_4/design_1_util_ds_buf_bin_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_bin_0 || ORIG_REF_NAME==design_1_util_ds_buf_bin_0}]

# IP: bd/design_1/ip/design_1_util_ds_buf_pwm_high_0_2/design_1_util_ds_buf_pwm_high_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_pwm_high_0 || ORIG_REF_NAME==design_1_util_ds_buf_pwm_high_0}]

# IP: bd/design_1/ip/design_1_util_ds_buf_pwm_low_0_2/design_1_util_ds_buf_pwm_low_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_pwm_low_0 || ORIG_REF_NAME==design_1_util_ds_buf_pwm_low_0}]

# IP: bd/design_1/ip/design_1_util_ds_buf_clkReturn_0_2/design_1_util_ds_buf_clkReturn_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_clkReturn_0 || ORIG_REF_NAME==design_1_util_ds_buf_clkReturn_0}]

# IP: bd/design_1/ip/design_1_xlslice_3_0_1/design_1_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_3_0 || ORIG_REF_NAME==design_1_xlslice_3_0}]

# IP: bd/design_1/ip/design_1_util_ds_buf_apins_0_4/design_1_util_ds_buf_apins_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_ds_buf_apins_0 || ORIG_REF_NAME==design_1_util_ds_buf_apins_0}]

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0}]

# XDC: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_100M_0}]

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==design_1_rst_processing_system7_0_100M_0}]

# XDC: bd/design_1/ip/design_1_rst_processing_system7_0_100M_0/design_1_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0}]

# XDC: bd/design_1/ip/design_1_axi_iic_0_0/design_1_axi_iic_0_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_modes_0_1/design_1_axi_gpio_modes_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_modes_0 || ORIG_REF_NAME==design_1_axi_gpio_modes_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_modes_0_1/design_1_axi_gpio_modes_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_modes_0_1/design_1_axi_gpio_modes_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_modes_0 || ORIG_REF_NAME==design_1_axi_gpio_modes_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_dac_0_1/design_1_axi_gpio_dac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_dac_0 || ORIG_REF_NAME==design_1_axi_gpio_dac_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_dac_0_1/design_1_axi_gpio_dac_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_dac_0_1/design_1_axi_gpio_dac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_dac_0 || ORIG_REF_NAME==design_1_axi_gpio_dac_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_abpins_0_1/design_1_axi_gpio_abpins_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_abpins_0 || ORIG_REF_NAME==design_1_axi_gpio_abpins_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_abpins_0_1/design_1_axi_gpio_abpins_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_abpins_0_1/design_1_axi_gpio_abpins_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_abpins_0 || ORIG_REF_NAME==design_1_axi_gpio_abpins_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_pwm_0_1/design_1_axi_gpio_pwm_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_pwm_0 || ORIG_REF_NAME==design_1_axi_gpio_pwm_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_pwm_0_1/design_1_axi_gpio_pwm_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_pwm_0_1/design_1_axi_gpio_pwm_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_pwm_0 || ORIG_REF_NAME==design_1_axi_gpio_pwm_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_clock_0_1/design_1_axi_gpio_clock_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_clock_0 || ORIG_REF_NAME==design_1_axi_gpio_clock_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_axi_gpio_clock_0_1/design_1_axi_gpio_clock_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_axi_gpio_clock_0_1/design_1_axi_gpio_clock_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_clock_0 || ORIG_REF_NAME==design_1_axi_gpio_clock_0}] {/U0 }]/U0 ]]

# XDC: bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_pat_0 || ORIG_REF_NAME==design_1_clk_pat_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_pat_0 || ORIG_REF_NAME==design_1_clk_pat_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0_late.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_pat_0 || ORIG_REF_NAME==design_1_clk_pat_0}] {/inst }]/inst ]]

# XDC: bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0_ooc.xdc

# XDC: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: bd/design_1/design_1_ooc.xdc
