set_property SRC_FILE_INFO {cfile:c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc rfile:../../../pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:design_1_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0.xdc rfile:../../../pat_testharness_fmc.srcs/sources_1/bd/design_1/ip/design_1_clk_pat_0_1/design_1_clk_pat_0.xdc id:2 order:EARLY scoped_inst:design_1_i/clk_pat_RnM/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Projects/June/pat_testharness_fmc/pat_testharness_fmc.srcs/constrs_1/imports/constraints/pat_testharness-constraints-fmc.xdc rfile:../../../pat_testharness_fmc.srcs/constrs_1/imports/constraints/pat_testharness-constraints-fmc.xdc id:3} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.1
set_property src_info {type:XDC file:3 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N20 [get_ports {gpio_modes_tri_io[0]}]
set_property src_info {type:XDC file:3 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J18 [get_ports {gpio_modes_tri_io[1]}]
set_property src_info {type:XDC file:3 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports {gpio_modes_tri_io[2]}]
set_property src_info {type:XDC file:3 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R21 [get_ports {gpio_modes_tri_io[3]}]
set_property src_info {type:XDC file:3 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R20 [get_ports {gpio_modes_tri_io[4]}]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {gpio_modes_tri_io[*]}]
set_property src_info {type:XDC file:3 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLDOWN true [get_ports {gpio_modes_tri_io[4]}]
set_property src_info {type:XDC file:3 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLDOWN true [get_ports {gpio_modes_tri_io[3]}]
set_property src_info {type:XDC file:3 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLDOWN true [get_ports {gpio_modes_tri_io[2]}]
set_property src_info {type:XDC file:3 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLDOWN true [get_ports {gpio_modes_tri_io[1]}]
set_property src_info {type:XDC file:3 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property PULLDOWN true [get_ports {gpio_modes_tri_io[0]}]
